name: flutter_application_1
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.2
  http: ^0.13.4
  dio: ^4.0.6
  uno: ^1.0.1+3
  flutter_modular: ^4.5.1+1

dev_dependencies:
  flutter_test:
    sdk: flutter
 
  mocktail: ^0.3.0
  
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
